//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnoTymBck.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransId { get; set; }
        public int UserId { get; set; }
        public int RefId { get; set; }
        public string TransType { get; set; }
        public decimal InisialAmount { get; set; }
        public decimal TransAmount { get; set; }
        public System.DateTime TransDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
